-- TransitOps PostgreSQL schema. The FastAPI startup hook also creates this model
-- metadata and seeds development credentials (all seeded users: password123).
CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(30) NOT NULL CHECK (role IN ('fleet_manager','dispatcher','safety_officer','financial_analyst')), department VARCHAR(100), status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active','inactive')), created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS vehicles (id SERIAL PRIMARY KEY, reg_no VARCHAR(20) UNIQUE NOT NULL, name VARCHAR(100) NOT NULL, type VARCHAR(30) NOT NULL CHECK (type IN ('Van','Truck','Bus','Bike','Other')), capacity DECIMAL(10,2) NOT NULL CHECK (capacity > 0), odometer DECIMAL(10,2) DEFAULT 0, acq_cost DECIMAL(12,2) NOT NULL, status VARCHAR(20) DEFAULT 'Available' CHECK (status IN ('Available','On Trip','In Shop','Retired')), region VARCHAR(50), created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS drivers (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, license_id VARCHAR(50) UNIQUE NOT NULL, category VARCHAR(20) NOT NULL, expiry_date DATE NOT NULL, safety_score DECIMAL(5,2) DEFAULT 100 CHECK (safety_score BETWEEN 0 AND 100), contact VARCHAR(15) NOT NULL, status VARCHAR(20) DEFAULT 'Available' CHECK (status IN ('Available','On Trip','Off Duty','Suspended')), created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS trips (id SERIAL PRIMARY KEY, code VARCHAR(20) UNIQUE NOT NULL, vehicle_id INTEGER REFERENCES vehicles(id), driver_id INTEGER REFERENCES drivers(id), source VARCHAR(100) NOT NULL, destination VARCHAR(100) NOT NULL, cargo_weight DECIMAL(10,2) NOT NULL CHECK (cargo_weight > 0), planned_distance DECIMAL(10,2) NOT NULL, actual_distance DECIMAL(10,2), fuel_consumed DECIMAL(10,2), final_odometer DECIMAL(10,2), status VARCHAR(20) DEFAULT 'Draft' CHECK (status IN ('Draft','Dispatched','Completed','Cancelled')), created_by INTEGER REFERENCES users(id), dispatched_at TIMESTAMP, completed_at TIMESTAMP, cancelled_at TIMESTAMP, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS maintenance_logs (id SERIAL PRIMARY KEY, vehicle_id INTEGER REFERENCES vehicles(id) ON DELETE CASCADE, service_type VARCHAR(100) NOT NULL, description TEXT, mechanic VARCHAR(100), est_cost DECIMAL(10,2) DEFAULT 0, status VARCHAR(20) DEFAULT 'In Shop' CHECK (status IN ('In Shop','Resolved')), date_logged TIMESTAMP DEFAULT NOW(), resolved_at TIMESTAMP, created_by INTEGER REFERENCES users(id));
CREATE TABLE IF NOT EXISTS expense_logs (id SERIAL PRIMARY KEY, type VARCHAR(30) NOT NULL CHECK (type IN ('Fuel','Toll','Maintenance','Parking','Other')), vehicle_id INTEGER REFERENCES vehicles(id), trip_id INTEGER REFERENCES trips(id), amount DECIMAL(10,2) NOT NULL CHECK (amount > 0), liters DECIMAL(10,2), description TEXT, date_logged DATE DEFAULT CURRENT_DATE, created_by INTEGER REFERENCES users(id), created_at TIMESTAMP DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_vehicles_status ON vehicles(status); CREATE INDEX IF NOT EXISTS idx_vehicles_type ON vehicles(type); CREATE INDEX IF NOT EXISTS idx_drivers_status ON drivers(status); CREATE INDEX IF NOT EXISTS idx_drivers_expiry ON drivers(expiry_date); CREATE INDEX IF NOT EXISTS idx_trips_status ON trips(status); CREATE INDEX IF NOT EXISTS idx_trips_vehicle ON trips(vehicle_id); CREATE INDEX IF NOT EXISTS idx_trips_driver ON trips(driver_id); CREATE INDEX IF NOT EXISTS idx_expenses_vehicle ON expense_logs(vehicle_id); CREATE INDEX IF NOT EXISTS idx_maintenance_vehicle ON maintenance_logs(vehicle_id);
CREATE OR REPLACE VIEW vehicle_cost_summary AS SELECT v.id, v.reg_no, v.name, v.acq_cost, v.status, COALESCE((SELECT SUM(e.amount) FROM expense_logs e WHERE e.vehicle_id=v.id AND e.type='Fuel'),0) AS total_fuel_cost, COALESCE((SELECT SUM(m.est_cost) FROM maintenance_logs m WHERE m.vehicle_id=v.id),0) AS total_maintenance_cost, COALESCE((SELECT SUM(e.amount) FROM expense_logs e WHERE e.vehicle_id=v.id),0)+COALESCE((SELECT SUM(m.est_cost) FROM maintenance_logs m WHERE m.vehicle_id=v.id),0) AS total_operational_cost, COALESCE((SELECT SUM(t.actual_distance) FROM trips t WHERE t.vehicle_id=v.id AND t.status='Completed'),0) AS total_distance, COALESCE((SELECT SUM(t.fuel_consumed) FROM trips t WHERE t.vehicle_id=v.id AND t.status='Completed'),0) AS total_fuel_consumed FROM vehicles v;
